version: '1'
services:
  microservicio1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@dy8adczjrluwz438_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=java_bd2
      - spring.datasource.password=ClaseFullStack1-
    restart: always